import { PRODUCTOS_NOTIFICATION_SECTIONS } from './sections';
// Notifications
import { PRODUCTOS_CATEGORIAS_NOTIFICATIONS } from './categorias.notifications';
import { PRODUCTOS_MARCAS_NOTIFICATIONS } from './marcas.notifications';
import { PRODUCTOS_PRODUCTOS_NOTIFICATIONS } from './productos.notifications';

export const PRODUCTOS_NOTIFICATIONS = {
    [PRODUCTOS_NOTIFICATION_SECTIONS.CATEGORIAS]: PRODUCTOS_CATEGORIAS_NOTIFICATIONS,
    [PRODUCTOS_NOTIFICATION_SECTIONS.MARCAS]: PRODUCTOS_MARCAS_NOTIFICATIONS,
    [PRODUCTOS_NOTIFICATION_SECTIONS.PRODUCTOS]: PRODUCTOS_PRODUCTOS_NOTIFICATIONS,
};
